In [1]:
import json
import pandas as pd
from skimpy import clean_columns

In [2]:
with open('facilities.json', 'r') as f:
    stations = json.load(f)

In [3]:
categories = sorted(set([facility['name'] for station in stations for facility in station['facilities']]))

In [4]:
flattened = []
for station in stations:
    new_station = { 'name': station['station'] }
    for category in categories:
        if category == 'Number of Parking Places for PMR':
            facility_description = next(iter([
                facility['value'] for facility in station['facilities']
                if facility['name'] == category
            ]), '0')
            new_station[category] = int(facility_description.replace('Nombre de places de parking PMR : ', ''))
        else:
            new_station[category] = int(category in [facility['name'] for facility in station['facilities']])
    flattened.append(new_station)

In [5]:
df = clean_columns(pd.DataFrame(flattened))
df

,name,blue_bikes_presence,cambio_information,escalator,free_toilets,has_pmr_assistance,lift_on_the_platform,location_of_taxis,luggage_lockers,number_of_parking_places_for_pmr,other_shared_bikes_in_the_area,pmr_toilets,paid_toilets,presence_of_connecting_buses,presence_of_connecting_metro,presence_of_connecting_tram,presence_of_the_bikes_point,tvm_count,wifi_presence
0,Anvers,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Anvers-Berchem,0,1,1,0,0,0,1,1,3,0,1,1,1,0,1,1,1,1
2,Anvers-Central,1,1,1,0,1,1,1,1,24,0,1,1,1,0,1,1,1,1
3,Anvers-Luchtbal,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0
4,Anvers-Noorderdokken,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561,Wervik,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0
562,Wevelgem,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
563,Zedelgem,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0
564,Zeebrugge-Dorp/Strand,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0
565,Zeebrugge-Dorp/Strand,1,0,0,0,0,0,1,0,7,0,0,0,1,0,0,0,1,0

In [6]:
df.to_csv('facilities_flattened.csv', index=False)